// Javascript Array Methods List
  // concat()
  // copyWithIn()
  // entries()
  // every()
  // fill()
  // filter()
  // find()
  // findIndex()
  // forEach()
  // Array.from()
  // includes()
  // indexOf()
  // isArray()
  // join()
  // lastIndexOf()
  // map()
  // push()
  // pop()
  // shift()
  // unshift()
  // reduce()
  // reverse()
  // slice()
  // some()  
  // sort()
  // splice()
  // toString()
  // values()

  